// Database ortaggi - calendario riferito a Emilia-Romagna (zona pianura)
// Mesi: 1 = Gennaio, 12 = Dicembre
// semina: in semenzaio o diretta in piena terra
// trapianto: dal semenzaio all'orto (giorni dopo la semina)
// raccolta: giorni dopo la semina o dopo il trapianto

const ORTAGGI = [
  {
    id: 'pomodoro',
    nome: 'Pomodoro',
    famiglia: 'Solanacee',
    emoji: '🍅',
    semina: { mesi: [2, 3, 4], tipo: 'semenzaio', profondita: '0.5 cm', distanza: '50 cm' },
    trapianto: { giorniDopoSemina: 50, mesi: [4, 5, 6] },
    raccolta: { giorniDopoTrapianto: 70, mesi: [7, 8, 9, 10] },
    suolo: 'Profondo, drenato, ricco di sostanza organica',
    annaffiatura: 'Regolare, evitando di bagnare le foglie',
    consociazioni: ['basilico', 'carota', 'prezzemolo'],
    nemici: ['cavolo', 'finocchio'],
    note: 'Necessita di sostegni. Sfemminellare i succhioni per varietà a crescita indeterminata.'
  },
  {
    id: 'zucchina',
    nome: 'Zucchina',
    famiglia: 'Cucurbitacee',
    emoji: '🥒',
    semina: { mesi: [3, 4, 5], tipo: 'semenzaio o diretta', profondita: '2 cm', distanza: '80 cm' },
    trapianto: { giorniDopoSemina: 30, mesi: [4, 5, 6] },
    raccolta: { giorniDopoTrapianto: 50, mesi: [6, 7, 8, 9, 10] },
    suolo: 'Ricco, ben concimato',
    annaffiatura: 'Abbondante, soprattutto durante la fruttificazione',
    consociazioni: ['fagiolo', 'mais', 'cipolla'],
    nemici: ['patata'],
    note: 'Raccogli i frutti giovani per stimolare nuove fioriture.'
  },
  {
    id: 'lattuga',
    nome: 'Lattuga',
    famiglia: 'Composite',
    emoji: '🥬',
    semina: { mesi: [1, 2, 3, 4, 5, 6, 7, 8, 9], tipo: 'semenzaio o diretta', profondita: '0.5 cm', distanza: '25 cm' },
    trapianto: { giorniDopoSemina: 30, mesi: [3, 4, 5, 6, 7, 8, 9, 10] },
    raccolta: { giorniDopoTrapianto: 40, mesi: [4, 5, 6, 7, 8, 9, 10, 11] },
    suolo: 'Sciolto, fresco',
    annaffiatura: 'Frequente e leggera',
    consociazioni: ['carota', 'ravanello', 'fragola'],
    nemici: ['prezzemolo'],
    note: 'Semina scalare ogni 15-20 giorni per raccolto continuo.'
  },
  {
    id: 'melanzana',
    nome: 'Melanzana',
    famiglia: 'Solanacee',
    emoji: '🍆',
    semina: { mesi: [2, 3], tipo: 'semenzaio caldo', profondita: '0.5 cm', distanza: '60 cm' },
    trapianto: { giorniDopoSemina: 70, mesi: [5, 6] },
    raccolta: { giorniDopoTrapianto: 80, mesi: [7, 8, 9, 10] },
    suolo: 'Profondo, ricco, ben drenato',
    annaffiatura: 'Regolare, mai eccessiva',
    consociazioni: ['fagiolino', 'spinacio'],
    nemici: ['pomodoro', 'patata'],
    note: 'Pianta delicata, ama il caldo. Pacciamare per mantenere umidità.'
  },
  {
    id: 'peperone',
    nome: 'Peperone',
    famiglia: 'Solanacee',
    emoji: '🌶️',
    semina: { mesi: [2, 3], tipo: 'semenzaio caldo', profondita: '0.5 cm', distanza: '50 cm' },
    trapianto: { giorniDopoSemina: 60, mesi: [5, 6] },
    raccolta: { giorniDopoTrapianto: 80, mesi: [7, 8, 9, 10] },
    suolo: 'Ricco, drenato',
    annaffiatura: 'Regolare alla base',
    consociazioni: ['basilico', 'carota', 'cipolla'],
    nemici: ['fagiolo', 'cavolo'],
    note: 'Ama il caldo. Tutori utili per varietà cariche di frutti.'
  },
  {
    id: 'fagiolo',
    nome: 'Fagiolo nano',
    famiglia: 'Leguminose',
    emoji: '🫘',
    semina: { mesi: [4, 5, 6, 7], tipo: 'diretta', profondita: '3 cm', distanza: '15 cm' },
    trapianto: null,
    raccolta: { giorniDopoSemina: 70, mesi: [6, 7, 8, 9] },
    suolo: 'Medio, non concimato fresco',
    annaffiatura: 'Moderata',
    consociazioni: ['carota', 'cetriolo', 'mais'],
    nemici: ['aglio', 'cipolla', 'porro'],
    note: 'Fissa azoto nel terreno. Semina scalare ogni 20 giorni.'
  },
  {
    id: 'fagiolino',
    nome: 'Fagiolino',
    famiglia: 'Leguminose',
    emoji: '🫛',
    semina: { mesi: [4, 5, 6, 7], tipo: 'diretta', profondita: '3 cm', distanza: '10 cm' },
    trapianto: null,
    raccolta: { giorniDopoSemina: 60, mesi: [6, 7, 8, 9] },
    suolo: 'Medio, ben drenato',
    annaffiatura: 'Regolare',
    consociazioni: ['carota', 'mais', 'pomodoro'],
    nemici: ['aglio', 'cipolla'],
    note: 'Raccogli giovani e teneri ogni 2-3 giorni.'
  },
  {
    id: 'pisello',
    nome: 'Pisello',
    famiglia: 'Leguminose',
    emoji: '🌱',
    semina: { mesi: [2, 3, 9, 10], tipo: 'diretta', profondita: '3 cm', distanza: '10 cm' },
    trapianto: null,
    raccolta: { giorniDopoSemina: 90, mesi: [5, 6, 11, 12] },
    suolo: 'Sciolto, ben drenato',
    annaffiatura: 'Moderata',
    consociazioni: ['carota', 'rapa', 'cetriolo'],
    nemici: ['aglio', 'cipolla', 'porro'],
    note: 'Le varietà rampicanti necessitano di sostegni.'
  },
  {
    id: 'carota',
    nome: 'Carota',
    famiglia: 'Ombrellifere',
    emoji: '🥕',
    semina: { mesi: [2, 3, 4, 5, 6, 7], tipo: 'diretta', profondita: '0.5 cm', distanza: '5 cm' },
    trapianto: null,
    raccolta: { giorniDopoSemina: 100, mesi: [6, 7, 8, 9, 10, 11] },
    suolo: 'Profondo, sciolto, senza sassi',
    annaffiatura: 'Regolare ma non eccessiva',
    consociazioni: ['cipolla', 'porro', 'lattuga'],
    nemici: ['aneto'],
    note: 'Diradare le piantine quando hanno 4-5 foglie.'
  },
  {
    id: 'cipolla',
    nome: 'Cipolla',
    famiglia: 'Liliacee',
    emoji: '🧅',
    semina: { mesi: [1, 2, 8, 9], tipo: 'semenzaio o bulbilli', profondita: '1 cm', distanza: '15 cm' },
    trapianto: { giorniDopoSemina: 60, mesi: [3, 4, 10] },
    raccolta: { giorniDopoTrapianto: 120, mesi: [6, 7, 8] },
    suolo: 'Sciolto, ben drenato',
    annaffiatura: 'Scarsa, sospendere prima della raccolta',
    consociazioni: ['carota', 'pomodoro', 'lattuga'],
    nemici: ['fagiolo', 'pisello'],
    note: 'Raccogli quando le foglie iniziano a piegarsi.'
  },
  {
    id: 'aglio',
    nome: 'Aglio',
    famiglia: 'Liliacee',
    emoji: '🧄',
    semina: { mesi: [10, 11, 12, 1, 2], tipo: 'bulbilli', profondita: '3 cm', distanza: '15 cm' },
    trapianto: null,
    raccolta: { giorniDopoSemina: 180, mesi: [6, 7] },
    suolo: 'Sciolto, ben drenato',
    annaffiatura: 'Scarsa',
    consociazioni: ['fragola', 'pomodoro', 'carota'],
    nemici: ['fagiolo', 'pisello', 'cavolo'],
    note: 'Raccogli quando 2/3 delle foglie sono ingiallite.'
  },
  {
    id: 'patata',
    nome: 'Patata',
    famiglia: 'Solanacee',
    emoji: '🥔',
    semina: { mesi: [2, 3, 4], tipo: 'tuberi-seme', profondita: '10 cm', distanza: '30 cm' },
    trapianto: null,
    raccolta: { giorniDopoSemina: 110, mesi: [6, 7, 8] },
    suolo: 'Sciolto, profondo',
    annaffiatura: 'Regolare fino alla fioritura',
    consociazioni: ['fagiolo', 'mais', 'cavolo'],
    nemici: ['pomodoro', 'zucchina', 'cetriolo'],
    note: 'Rincalzare 2-3 volte durante la crescita.'
  },
  {
    id: 'spinacio',
    nome: 'Spinacio',
    famiglia: 'Chenopodiacee',
    emoji: '🥬',
    semina: { mesi: [2, 3, 8, 9, 10], tipo: 'diretta', profondita: '1 cm', distanza: '15 cm' },
    trapianto: null,
    raccolta: { giorniDopoSemina: 50, mesi: [4, 5, 10, 11, 12] },
    suolo: 'Ricco, fresco',
    annaffiatura: 'Frequente',
    consociazioni: ['fragola', 'cavolo', 'ravanello'],
    nemici: ['barbabietola'],
    note: 'Va in semina con caldo. Preferisci stagioni fresche.'
  },
  {
    id: 'cavolo',
    nome: 'Cavolo',
    famiglia: 'Crucifere',
    emoji: '🥬',
    semina: { mesi: [2, 3, 6, 7], tipo: 'semenzaio', profondita: '0.5 cm', distanza: '50 cm' },
    trapianto: { giorniDopoSemina: 40, mesi: [4, 5, 8, 9] },
    raccolta: { giorniDopoTrapianto: 100, mesi: [7, 8, 11, 12, 1] },
    suolo: 'Profondo, ricco',
    annaffiatura: 'Regolare e abbondante',
    consociazioni: ['sedano', 'spinacio', 'patata'],
    nemici: ['pomodoro', 'fragola', 'aglio'],
    note: 'Attenzione alla cavolaia (farfalla bianca).'
  },
  {
    id: 'broccolo',
    nome: 'Broccolo',
    famiglia: 'Crucifere',
    emoji: '🥦',
    semina: { mesi: [3, 4, 6, 7], tipo: 'semenzaio', profondita: '0.5 cm', distanza: '50 cm' },
    trapianto: { giorniDopoSemina: 40, mesi: [5, 6, 8, 9] },
    raccolta: { giorniDopoTrapianto: 90, mesi: [8, 9, 10, 11, 12] },
    suolo: 'Profondo, ricco',
    annaffiatura: 'Regolare',
    consociazioni: ['sedano', 'spinacio', 'patata'],
    nemici: ['pomodoro', 'fragola'],
    note: 'Raccogli prima che i fiori si aprano.'
  },
  {
    id: 'finocchio',
    nome: 'Finocchio',
    famiglia: 'Ombrellifere',
    emoji: '🌿',
    semina: { mesi: [4, 5, 6, 7, 8], tipo: 'semenzaio o diretta', profondita: '0.5 cm', distanza: '25 cm' },
    trapianto: { giorniDopoSemina: 30, mesi: [5, 6, 7, 8, 9] },
    raccolta: { giorniDopoTrapianto: 90, mesi: [8, 9, 10, 11, 12] },
    suolo: 'Sciolto, ben drenato',
    annaffiatura: 'Regolare',
    consociazioni: ['cetriolo', 'porro'],
    nemici: ['pomodoro', 'fagiolo', 'cavolo'],
    note: 'Rincalzare il colletto per ottenere grumoli bianchi.'
  },
  {
    id: 'sedano',
    nome: 'Sedano',
    famiglia: 'Ombrellifere',
    emoji: '🌿',
    semina: { mesi: [2, 3, 4], tipo: 'semenzaio', profondita: '0.5 cm', distanza: '30 cm' },
    trapianto: { giorniDopoSemina: 60, mesi: [5, 6] },
    raccolta: { giorniDopoTrapianto: 100, mesi: [8, 9, 10, 11] },
    suolo: 'Ricco, fresco, profondo',
    annaffiatura: 'Abbondante e regolare',
    consociazioni: ['cavolo', 'pomodoro', 'fagiolo'],
    nemici: ['mais', 'prezzemolo'],
    note: 'Imbianchire i gambi legandoli o coprendoli.'
  },
  {
    id: 'porro',
    nome: 'Porro',
    famiglia: 'Liliacee',
    emoji: '🌱',
    semina: { mesi: [2, 3, 4], tipo: 'semenzaio', profondita: '1 cm', distanza: '15 cm' },
    trapianto: { giorniDopoSemina: 60, mesi: [5, 6, 7] },
    raccolta: { giorniDopoTrapianto: 120, mesi: [9, 10, 11, 12, 1] },
    suolo: 'Sciolto, ricco',
    annaffiatura: 'Regolare',
    consociazioni: ['carota', 'sedano', 'cipolla'],
    nemici: ['fagiolo', 'pisello'],
    note: 'Rincalzare il fusto per ottenere parte bianca lunga.'
  },
  {
    id: 'ravanello',
    nome: 'Ravanello',
    famiglia: 'Crucifere',
    emoji: '🌶️',
    semina: { mesi: [2, 3, 4, 5, 6, 7, 8, 9], tipo: 'diretta', profondita: '1 cm', distanza: '5 cm' },
    trapianto: null,
    raccolta: { giorniDopoSemina: 30, mesi: [3, 4, 5, 6, 7, 8, 9, 10] },
    suolo: 'Sciolto, fresco',
    annaffiatura: 'Frequente',
    consociazioni: ['carota', 'lattuga', 'spinacio'],
    nemici: ['vite'],
    note: 'Crescita rapida: ideale per riempire spazi tra altre colture.'
  },
  {
    id: 'cetriolo',
    nome: 'Cetriolo',
    famiglia: 'Cucurbitacee',
    emoji: '🥒',
    semina: { mesi: [3, 4, 5], tipo: 'semenzaio o diretta', profondita: '2 cm', distanza: '60 cm' },
    trapianto: { giorniDopoSemina: 30, mesi: [5, 6] },
    raccolta: { giorniDopoTrapianto: 60, mesi: [7, 8, 9] },
    suolo: 'Ricco, ben concimato',
    annaffiatura: 'Abbondante',
    consociazioni: ['fagiolo', 'mais', 'pisello'],
    nemici: ['patata', 'salvia'],
    note: 'Fornire sostegni se vuoi crescita verticale.'
  },
  {
    id: 'zucca',
    nome: 'Zucca',
    famiglia: 'Cucurbitacee',
    emoji: '🎃',
    semina: { mesi: [4, 5], tipo: 'semenzaio o diretta', profondita: '3 cm', distanza: '150 cm' },
    trapianto: { giorniDopoSemina: 30, mesi: [5, 6] },
    raccolta: { giorniDopoTrapianto: 110, mesi: [9, 10, 11] },
    suolo: 'Profondo, ricchissimo',
    annaffiatura: 'Abbondante in fioritura',
    consociazioni: ['mais', 'fagiolo', 'ravanello'],
    nemici: ['patata'],
    note: 'Richiede molto spazio. Ideale dopo letamazione.'
  },
  {
    id: 'bietola',
    nome: 'Bietola da costa',
    famiglia: 'Chenopodiacee',
    emoji: '🥬',
    semina: { mesi: [3, 4, 5, 6, 7, 8], tipo: 'diretta', profondita: '2 cm', distanza: '30 cm' },
    trapianto: null,
    raccolta: { giorniDopoSemina: 60, mesi: [5, 6, 7, 8, 9, 10, 11] },
    suolo: 'Ricco, fresco',
    annaffiatura: 'Regolare',
    consociazioni: ['cavolo', 'cipolla', 'fagiolo'],
    nemici: ['spinacio'],
    note: 'Raccogli foglie esterne per produzione continua.'
  },
  {
    id: 'rucola',
    nome: 'Rucola',
    famiglia: 'Crucifere',
    emoji: '🌿',
    semina: { mesi: [3, 4, 5, 6, 7, 8, 9], tipo: 'diretta', profondita: '0.5 cm', distanza: '15 cm' },
    trapianto: null,
    raccolta: { giorniDopoSemina: 30, mesi: [4, 5, 6, 7, 8, 9, 10] },
    suolo: 'Medio',
    annaffiatura: 'Frequente',
    consociazioni: ['lattuga', 'fagiolo'],
    nemici: [],
    note: 'Cresce rapidamente. Semina scalare ogni 15 giorni.'
  },
  {
    id: 'basilico',
    nome: 'Basilico',
    famiglia: 'Labiate',
    emoji: '🌿',
    semina: { mesi: [3, 4, 5], tipo: 'semenzaio o diretta', profondita: '0.5 cm', distanza: '20 cm' },
    trapianto: { giorniDopoSemina: 40, mesi: [5, 6] },
    raccolta: { giorniDopoTrapianto: 30, mesi: [6, 7, 8, 9] },
    suolo: 'Sciolto, fertile',
    annaffiatura: 'Regolare al mattino',
    consociazioni: ['pomodoro', 'peperone'],
    nemici: ['ruta'],
    note: 'Cima i fiori per favorire produzione di foglie.'
  },
  {
    id: 'prezzemolo',
    nome: 'Prezzemolo',
    famiglia: 'Ombrellifere',
    emoji: '🌿',
    semina: { mesi: [2, 3, 4, 5, 6, 7, 8], tipo: 'diretta', profondita: '0.5 cm', distanza: '20 cm' },
    trapianto: null,
    raccolta: { giorniDopoSemina: 70, mesi: [4, 5, 6, 7, 8, 9, 10, 11] },
    suolo: 'Sciolto, fresco',
    annaffiatura: 'Regolare',
    consociazioni: ['pomodoro', 'asparago', 'rosa'],
    nemici: ['lattuga'],
    note: 'Germinazione lenta: tieni umido il terreno per 2-3 settimane.'
  }
];
